FROM golang:1.23 AS build

WORKDIR /
COPY . .

RUN go mod download
RUN CGO_ENABLED=0 go build -o cron cmd/cronjob/cronjob.go

FROM gcr.io/distroless/static-debian11
WORKDIR /app

COPY --from=build cron cron
COPY --from=build /migrations ./migrations

ENTRYPOINT ["/app/cron"]
