// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Repositories --
	CountRepositories(ctx context.Context, dollar_1 string) (int64, error)
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) error
	CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) error
	FetchSecurityPullRequests(ctx context.Context) ([]FetchSecurityPullRequestsRow, error)
	GetAllRepositories(ctx context.Context) ([]Repository, error)
	// Pull Requests (prs) --
	GetLastPullRequestMergedDate(ctx context.Context, arg GetLastPullRequestMergedDateParams) (pgtype.Timestamptz, error)
	// Commits --
	InsertCommit(ctx context.Context, arg InsertCommitParams) error
	// Use ILIKE for case-insensitive search, handle empty search string
	ListRepositories(ctx context.Context, arg ListRepositoriesParams) ([]Repository, error)
	TruncateRepositories(ctx context.Context) error
	// Teams --
	TruncateTeams(ctx context.Context) error
	UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) error
	// Pull Request Reviews --
	UpsertPullRequestReview(ctx context.Context, arg UpsertPullRequestReviewParams) error
}

var _ Querier = (*Queries)(nil)
